### ISSUE TITLE
Unable to install via npm

### ISSUE THREAD

**Issue by Fuitad** [vibornoff/node-yajl#3]
Heya, I've been trying to install node-yajl via npm using OSX and CentOS and I'm getting the exact same error on both. I've tried node 0.4.11 and node 0.5.5 without any luck. Any ideas what could be wrong?

```
$ npm install yajl

> yajl@0.6.1 install /Volumes/Fuitad/node_modules/yajl
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /opt/local/lib/node 
Checking for node prefix                 : ok /opt/local 
Checking for header yajl/yajl_version.h  : yes 
'configure' finished successfully (0.118s)
Waf: Entering directory `/Volumes/Fuitad/node_modules/yajl/build'
[1/4] cxx: src/yajl.cc -> build/Release/src/yajl_1.o
[2/4] cxx: src/handle.cc -> build/Release/src/handle_1.o
[3/4] cxx: src/tree.cc -> build/Release/src/tree_1.o
In file included from ../src/yajl.cc:33:
../src/handle.h:35:30: error: node/node_events.h: No such file or directory
../src/handle.cc:32:30: error: node/node_events.h: No such file or directory
../src/tree.cc:19:35: error: node/node_object_wrap.h: No such file or directory
In file included from ../src/yajl.cc:33:
../src/handle.h:41: error: expected class-name before ‘{’ token
In file included from ../src/handle.cc:35:
../src/handle.h:41: error: expected class-name before ‘{’ token
../src/handle.cc: In static member function ‘static void yajljs::Handle::Initialize(v8::Handle<v8::Object>)’:
../src/handle.cc:66: error: ‘EventEmitter’ has not been declared
../src/handle.cc: In static member function ‘static v8::Handle<v8::Value> yajljs::Handle::New(const v8::Arguments&)’:
../src/handle.cc:95: error: ‘class yajljs::Handle’ has no member named ‘Wrap’
../src/handle.cc: In constructor ‘yajljs::Handle::Handle(yajl_option)’:
../src/handle.cc:100: error: class ‘yajljs::Handle’ does not have any field named ‘EventEmitter’
../src/handle.cc: In static member function ‘static v8::Handle<v8::Value> yajljs::Handle::Parse(const v8::Arguments&)’:
../src/handle.cc:135: error: ‘Unwrap’ was not declared in this scope
../src/handle.cc:135: error: expected primary-expression before ‘>’ token
../src/handle.cc: In static member function ‘static v8::Handle<v8::Value> yajljs::Handle::CompleteParse(const v8::Arguments&)’:
../src/handle.cc:145: error: ‘Unwrap’ was not declared in this scope
../src/handle.cc:145: error: expected primary-expression before ‘>’ token
../src/handle.cc: In static member function ‘static v8::Handle<v8::Value> yajljs::Handle::GetBytesConsumed(const v8::Arguments&)’:
../src/handle.cc:155: error: ‘Unwrap’ was not declared in this scope
../src/handle.cc:155: error: expected primary-expression before ‘>’ token
../src/handle.cc: In member function ‘int yajljs::Handle::Parse(unsigned char*, int)’:
../src/handle.cc:168: error: ‘Emit’ was not declared in this scope
../src/handle.cc: In member function ‘void yajljs::Handle::CompleteParse()’:
../src/handle.cc:182: error: ‘Emit’ was not declared in this scope
../src/handle.cc: In function ‘int yajljs::OnNull(void*)’:
../src/handle.cc:195: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnBoolean(void*, int)’:
../src/handle.cc:203: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnInteger(void*, long long int)’:
../src/handle.cc:212: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnDouble(void*, double)’:
../src/handle.cc:221: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnNumber(void*, const char*, size_t)’:
../src/handle.cc:230: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnString(void*, const unsigned char*, size_t)’:
../src/handle.cc:238: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnStartMap(void*)’:
../src/handle.cc:245: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnMapKey(void*, const unsigned char*, size_t)’:
../src/handle.cc:253: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnEndMap(void*)’:
../src/handle.cc:260: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnStartArray(void*)’:
../src/handle.cc:267: error: ‘class yajljs::Handle’ has no member named ‘Emit’
../src/handle.cc: In function ‘int yajljs::OnEndArray(void*)’:
../src/handle.cc:274: error: ‘class yajljs::Handle’ has no member named ‘Emit’
Waf: Leaving directory `/Volumes/Fuitad/node_modules/yajl/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx yajl.cc -> yajl_1.o}
 -> task failed (err #1): 
    {task: cxx handle.cc -> handle_1.o}
 -> task failed (err #1): 
    {task: cxx tree.cc -> tree_1.o}
npm ERR! error installing yajl@0.6.1 Error: yajl@0.6.1 install: `node-waf configure build`
npm ERR! error installing yajl@0.6.1 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing yajl@0.6.1     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing yajl@0.6.1     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing yajl@0.6.1     at ChildProcess.onexit (child_process_legacy.js:246:12)
npm ERR! yajl@0.6.1 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the yajl@0.6.1 install script.
npm ERR! This is most likely a problem with the yajl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls yajl
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.1.0
npm ERR! command "node" "/opt/local/bin/npm" "install" "yajl"
npm ERR! cwd /Volumes/Fuitad
npm ERR! node -v v0.5.5
npm ERR! npm -v 1.0.27
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Volumes/Fuitad/npm-debug.log
npm not ok
```

**Comment by choccy** [comment]
Bump..?

**Comment by scttnlsn** [comment]
I'm having a similar problem on OS X Lion.  I installed yajl via Homebrew.

**Comment by scttnlsn** [comment]
C++ EventEmitter was removed Node v0.5.x

**Comment by kilianc** [comment]
+1

**Comment by vibornoff** [comment]
Could you please post `npm` output here?

**Comment by scttnlsn** [comment]
Issue #4 fixes this.
