### ISSUE TITLE
unable to install via npm

### ISSUE THREAD

**Issue by yuri-karadzhov** [vibornoff/node-yajl#5]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.6.9-030609-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/skwibl/node_modules/yajl
gyp ERR! node -v v0.8.15
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok 
npm ERR! yajl@0.8.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the yajl@0.8.1 install script.
npm ERR! This is most likely a problem with the yajl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls yajl
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.6.9-030609-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! cwd /var/www/skwibl
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/skwibl/npm-debug.log
npm ERR! not ok code 0

**Comment by andreaspitzer** [comment]
+1

**Comment by simpleseeker** [comment]
+1 I got the same problem. Does Anyone know how to resolve this?

**Comment by imamtauhid** [comment]
+1

**Comment by jmarca** [comment]
With node v5.*, it seems the bindings here are out of date.  I took a look at updating the bindings etc, based on the version 5 node.js docs, but I have no clue what I'm doing.  

I have yajl  v 2.0.4 on my linux system, running node v5.7.0, node-gyp version 3.3.0, npm version 3.7.5
