### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by pocesar** [vibornoff/node-yajl#6]
```
npm http GET http://registry.npmjs.org/yajl/-/yajl-0.8.1.tgz
npm http 200 http://registry.npmjs.org/yajl/-/yajl-0.8.1.tgz

> yajl@0.8.1 install C:\Users\Webdev\...\node_modules\jsonrpc-tcp\node_modules\jsonsp\node_modules\yajl
> node-gyp rebuild

C:\Users\Webdev\...\node_modules\jsonrpc-tcp\node_modules\jsonsp\node_modules\yajl>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  yajl.cc
  handle.cc
..\src\handle.cc(34): fatal error C1083: Cannot open include file: 'yajl/yajl_parse.h': No such file or directory [C:\Users\Webdev\...\node_modules\jsonrpc-tcp\node_modules\jsonsp\node_modules\yajl\build\yajl.vcxproj]
c:\users\webdev\...\node_modules\jsonrpc-tcp\node_modules\jsonsp\node_modules\yajl\src\handle.hh(36): fatal error C1083: Cannot open include f
ile: 'yajl/yajl_parse.h': No such file or directory (..\src\yajl.cc) [C:\Users\Webdev\...\node_modules\jsonrpc-tcp\node_modules\jsonsp\node_mo
dules\yajl\build\yajl.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Webdev\...\node_modules\jsonrpc-tcp\node_modules\jsonsp\node_modules\yajl
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok
unbuild yajl@0.8.1
unbuild jsonsp@0.2.0
unbuild jsonrpc-tcp@0.1.0
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by abrkn** [comment]
:+1:

**Comment by vibornoff** [comment]
You had to have _libyajl2_ installed along with its development headers.

Not sure about Windows, I haven't deal with it for a long long time, it should be _yajl2.dll_ binary. I don't know how Node handles external dependancies. If you have any clue feel free to participate into this issue.
